### PR TITLE
fix: an exception caused by an object's key being set twice

### PR DESCRIPTION
**Pull request by rectcircle**

### CODE REVIEW

**Comment by mmacfadden** [comment]
Thanks for submitting. I will review shortly.

**Comment by mmacfadden** [comment]
@rectcircle Greetings. Looking at the code change, it definitely seems correct. However, I am trying to create a unit test or scenario that will show the bug. Could you tell me what steps lead to you seeing this exception.  I'll get it merged, and we can get this snuck into the release that is actually coming out this weekend!

**Review by mmacfadden — APPROVED** [review]
Looks good to me.

**Comment by rectcircle** [comment]
session RealTimeObject.set(key, value)

**Comment by rectcircle** [comment]
if not fix this bug, You can reproduce like this:

* sessionA: RealTimeObject.set(key, value1)
* sessionB: RealTimeObject.set(key, value2)
* the `object[key]` will detach (can assert noop = true)

PS: This bug was discovered by my colleague, thank him. (translate by google)

**Pull request merged**
